apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-v1
  namespace: fintrack
spec:
  replicas: 2
  selector: { matchLabels: { app: account-service, version: v1 } }
  template:
    metadata: { labels: { app: account-service, version: v1 } }
    spec:
      containers:
      - name: account-service
        image: coshik/account-service:v1
        env: [{ name: VERSION, value: "v1" }]
        ports: [{ containerPort: 5000 }]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-v2
  namespace: fintrack
spec:
  replicas: 1
  selector: { matchLabels: { app: account-service, version: v2 } }
  template:
    metadata: { labels: { app: account-service, version: v2 } }
    spec:
      containers:
      - name: account-service
        image: coshik/account-service:v2
        env: [{ name: VERSION, value: "v2" }]
        ports: [{ containerPort: 5000 }]
        resources:
          limits: { memory: "50Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: fintrack
spec:
  selector: { app: account-service }
  ports: [{ port: 5000 }]
